#
# Copyright (c) 2021-2022 zPonds <https://shinenet.cn>
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the GPL License.
# See /LICENSE for more information.
#
# https://github.com/Erope/openwrt_nezha/
# Description: Build Nezha using GitHub Actions
#

name: Build NeZha Ipk

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

env:
  REPO_URL: https://git.openwrt.org/openwrt/openwrt.git
  REPO_CHECKOUT: v24.10.0
  FEEDS_CONF: feeds.conf.default
  EXTERNAL_FILE: configs/luci/nezha.config
  UPLOAD_BIN_DIR: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ovh
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clone source code
      run: |
        df -hT $PWD
        git clone $REPO_URL openwrt
        ln -sf ./openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        git checkout $REPO_CHECKOUT
        make distclean
        echo 'src-git nezha https://github.com/dysf888/OpenWRT_NeZha_V1' >> feeds.conf.default

    - name: Update feeds
      run: cd openwrt && ./scripts/feeds update -a

    - name: Install feeds
      run: cd openwrt && ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        ARCH_CONFIG="configs/${{ matrix.arch }}.config"
        if [ -e "$ARCH_CONFIG" ]; then
          mv "$ARCH_CONFIG" openwrt/.config
        fi

    - name: Modify configuration
      run: |
        cat $EXTERNAL_FILE >> openwrt/.config
        export FORCE_UNSAFE_CONFIGURE=1
        cd openwrt && make defconfig
        cat .config

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: Download
      run: |
        cd openwrt
        make download -j$(nproc) V=s

    - name: Compile the BIN
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) toolchain/install
        make -j$(nproc) package/feeds/nezha/openwrt-nezha/compile V=s
        make -j$(nproc) package/feeds/nezha/luci-app-nezha-agent-v1/compile V=s
        echo "::set-output name=status::success"

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: OpenWrt_bin_${{ matrix.arch }}_${{ env.FILE_DATE }}
        path: openwrt/bin

    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        echo "::set-output name=release_tag::$(curl -m 10 -sL "https://api.github.com/repos/nezhahq/agent/releases/latest" | grep "tag_name" | head -n 1 | awk -F ":" '{print $2}' | sed 's/\"//g;s/,//g;s/ //g')"
        touch release.txt
        echo "::set-output name=status::success"

    - name: Upload BIN to release
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: |
          openwrt/bin/packages/x86_64/nezha/*
          openwrt/bin/packages/x86_64/packages/lyaml*
          openwrt/bin/packages/aarch64_armv8-a/nezha/*
          openwrt/bin/packages/aarch64_armv8-a/packages/lyaml*